### ISSUE TITLE
Gulp raphael + moment not found

### ISSUE THREAD

**Issue by DigitalCoder** [krisanalfa/laravel-adminlte#2]
$ gupl (enter)

result : 
Fetching Copy Source Files...
- bower_components/raphael/raphael.js <-- Not Found

Fetching Copy Source Files...
- bower_components/raphael/raphael-min.js <-- Not Found

Fetching Copy Source Files...
- node_modules/momentmoment.js <-- Not Found

**Comment by DigitalCoder** [comment]
Resolved !

I've installed raphael and moment with npm,
then change the path in gulpfile.js

**Comment by krisanalfa** [comment]
Would you mind to share your `gulpfile.js` file?
